extends:
  - eslint:all
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
root: true
ignorePatterns:
  - typechain-types/**
rules:
  capitalized-comments: ["error", "always", { "ignoreConsecutiveComments": true }]
  multiline-comment-style: ["error", "separate-lines"]
  no-console: off
  no-warning-comments: warn
  one-var: ["error", "never"]
overrides:
  - files: [test/**/*.ts]
    rules:
      no-await-in-loop: ["off"]


