name: Build and test

on:
  push:
    branches-ignore:
      - 'docs-*'
  pull_request:
    branches-ignore:
      - 'docs-*'

env:
  PYTHON_VERSION: 3.11

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Install NODE JS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install project
      run: yarn install

    - name: Install slither
      run: pip3 install -r scripts/requirements.txt

    - name: Check spelling
      run: yarn cspell

    - name: Lint
      run: yarn fullCheck

    - name: Test deployment
      run: ./scripts/test_deploy.sh

    # - name: Test upgrade
    #   env:
    #     NODE_VERSION: ${{ matrix.node-version }}
    #   run: ./scripts/test_upgrade.sh

    # - name: Test ABI generation
    #   run: npx hardhat run scripts/generateAbi.ts

    - name: Run tests
      run: yarn exec hardhat coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

